11

diff --git a/.github/workflows/kubeadm-image-export-amd.yml b/.github/workflows/kubeadm-image-export-amd.yml
--- a/.github/workflows/kubeadm-image-export-amd.yml
+++ b/.github/workflows/kubeadm-image-export-amd.yml
@@ -42,11 +42,19 @@ jobs:
 
       - name: Install kubeadm
         run: |
+          K8S_VERSION_NUM=${K8S_VERSION#v}
           sudo apt-get update
           sudo apt-get install -y apt-transport-https ca-certificates curl
           sudo echo "deb [trusted=yes] https://mirrors.aliyun.com/kubernetes/apt/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list > /dev/null
           sudo apt-get update --allow-unauthenticated
-          sudo apt-get install -y kubeadm --allow-unauthenticated
+          # sudo apt-get install -y kubeadm --allow-unauthenticated
+          # 自动获取完整版本号
+          DEB_KUBEADM_VERSION=$(apt-cache madison kubeadm | grep ${K8S_VERSION_NUM} | head -n1 | awk '{print $3}')
+          if [ -z "$DEB_KUBEADM_VERSION" ]; then
+            echo "❌ kubeadm version ${K8S_VERSION_NUM} not found!"
+            exit 1
+          fi
+          sudo apt-get install -y kubeadm=$DEB_KUBEADM_VERSION --allow-unauthenticated
 
       # - name: Pull images with kubeadm
       #   run: |
